services:
  hub:
    image: selenium/hub:4.32
    ports:
      - 4444:4444
      - 4443:4443
      - 4442:4442
  chrome:
    image: selenium/node-chromium:4.32
    shm_size: 2g
    depends_on:
      - hub
    deploy:
      replicas: 0
    env_file: .env
  firefox:
    image: selenium/node-firefox:4.32
    shm_size: 2g
    depends_on:
      - hub
    deploy:
      replicas: 0
    env_file: .env