services:
  hub:
    image: selenium/hub:4.32
    ports:
      - 4444:4444
      - 4443:4443
      - 4442:4442
  chrome:
    image: selenium/node-chromium:4.32
    shm_size: 2g
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_VNC_NO_PASSWORD=1
  firefox:
    image: selenium/node-firefox:4.32
    shm_size: 2g
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_VNC_NO_PASSWORD=1
